### ISSUE TITLE
Any idea why this is happening ?

### ISSUE THREAD

**Issue by lukepolo** [YOzaz/Laravel-SwiftMailer#6]
[2016-05-05 17:11:36] production.ERROR: ErrorException: fwrite(): send of 18 bytes failed with errno=32 Broken pipe in /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:232
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'fwrite(): send ...', '/var/www/html/p...', 232, Array)
#1 /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(232): fwrite(Resource id #533, 'RSET\r\nQUIT\r\nQUI...')
#2 /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(173): Swift_Transport_StreamBuffer->_commit('RSET\r\nQUIT\r\nQUI...')
#3 /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(92): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('RSET\r\nQUIT\r\nQUI...')
#4 /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(276): Swift_ByteStream_AbstractFilterableInputStream->write('QUIT\r\n')
#5 /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('QUIT\r\n', Array, Array)
#6 /var/www/html/prod/forcebook/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(216): Swift_Transport_EsmtpTransport->executeCommand('QUIT\r\n', Array)
#7 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(307): Swift_Transport_AbstractSmtpTransport->stop()
#8 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(151): Illuminate\Mail\Mailer->forceReconnection()
#9 [internal function]: Illuminate\Mail\Mailer->send('pto.email.pto_u...', Array, Object(Closure))
#10 /var/www/html/prod/forcebook/vendor/yozaz/laravel-swiftmailer/src/YOzaz/LaravelSwiftmailer/Mailer.php(372): call_user_func_array(Array, Array)
#11 /var/www/html/prod/forcebook/vendor/yozaz/laravel-swiftmailer/src/YOzaz/LaravelSwiftmailer/Mailer.php(346): YOzaz\LaravelSwiftmailer\Mailer->__call('send', Array)
#12 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): YOzaz\LaravelSwiftmailer\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#13 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#14 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(207): Illuminate\Queue\Jobs\DatabaseJob->fire()
#15 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(155): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '3', 0)
#16 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '10', '3')
#17 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, 0, '10', '3')
#18 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(103): Illuminate\Queue\Worker->daemon(NULL, NULL, 0, 128, '10', '3')
#19 /var/www/html/prod/forcebook/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, true)
#20 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()

**Comment by YOzaz** [comment]
See here: https://github.com/laravel/framework/issues/4573#issuecomment-211996632 - it looks like Laravel 5.x patch is not working correctly.
Honestly, I don't know how to solve this, as this is in Laravel framework itself. Maybe disable autorestart function in Laravel source directly, until Taylor will sort it out?

Also, it is possible that your Beanstalkd pipe size is too small (try increasing it in config).

**Comment by lukepolo** [comment]
WIll just close this , just resorted to restarting my queues every 15 min......

**Comment by YOzaz** [comment]
Just for the heads update - this should be solved in latest release.
